name: my_pdf_viewer
description: A simple PDF viewer app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_pdfviewer: ^23.1.44
  file_picker: ^8.0.0
  shared_preferences: ^2.2.3
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

#name: my_pdf_viewer
#description: A new Flutter project.

#version: 1.0.0+1

#environment:
  #sdk: ">=3.0.0 <4.0.0"

#dependencies:
  #flutter:
    #sdk: flutter
  # other dependencies...

#dev_dependencies:
  #flutter_test:
    #sdk: flutter
  #flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/pdf.png"

flutter:
  uses-material-design: true

